### ISSUE TITLE
Cambio de letra en Windows

### ISSUE THREAD

**Issue by VJarreta** [VJarreta/unizar-vv-catmdedit#3]
**Is your feature request related to a problem? Please describe.**

Feature 2.5 hoja excel

No se encuentra de forma sencilla la posibilidad de cambiar el tamaño de letra para el sistema operativo Windows 7.

**Describe the solution you'd like**
En la configuración del Software la opción de cambiar el tamaño de letra.

@723553 
@VJarreta

**Comment by ediazl** [comment]
No se va a arreglar, solucionado. #4
