### ISSUE TITLE
El tamaño de letra no cambia en CentOS

### ISSUE THREAD

**Issue by GabrielCiberseguridad** [VJarreta/unizar-vv-catmdedit#4]
**Describe the bug**
Bug 2.5 hoja excel.

El tamaño de letra no es posible cambiarlo en CentOS. Hay un fichero ".properties" que permite cambiar el tamaña. atendiendo a las etiquetas que tiene. Sin embargo, a pesar de modificar el número del tamaño de letra en la etiqueta correspondiente, el tamaño de letra no se cambia
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

@VJarreta @723553

**Comment by ediazl** [comment]
Este error no se va a arreglar, solucionado.
